services:
  scraper:
    build: .
    env_file:
      - LetMeRent/.env
    entrypoint: ["/app/scripts/run_all_spiders.sh"]
    command: []
    networks:
      - mongodb_dev_net

networks:
  mongodb_dev_net:
    external: true
